steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
    '-t',
    'us.gcr.io/${_GCLOUD_PROJECT}/atddocker_consoleservice:${_VERSION}',
    'consoleservice/.']
substitutions:
  _GCLOUD_PROJECT: atd-testdrivetraining-dev
  _VERSION: "1.0.0"
images: [
  'us.gcr.io/${_GCLOUD_PROJECT}/atddocker_consoleservice:${_VERSION}',
]
