"""
Bridge Utilities - Single Source of Truth for Bridge Naming

This module provides the canonical implementation for:
- Device name abbreviation (for bridge name generation)
- Bridge name generation (OVS bridge naming convention)
- Bridge name parsing (reverse lookup for display)

All other modules should import from here to ensure consistency
between bridge generation and parsing across services.

Bridge Name Format (nodebuilder convention):
    {dev1_code}x{port1_code}-{dev2_code}x{port2_code}
    Example: le5x1-sp4x9 (leaf5 Ethernet1 to spine4 Ethernet9)

Device Abbreviations:
    First 2 letters of device type + device number
    Examples: spine1 -> sp1, borderleaf1 -> bo1, firewall1 -> fi1
"""

import hashlib
import logging
import re
from typing import Dict, Optional, Tuple

logger = logging.getLogger('nodebuilder.bridge_utils')


# =============================================================================
# DEVICE ABBREVIATIONS - Single Source of Truth
# =============================================================================
# Used by both generation (device_name -> code) and parsing (code -> device_name)
#
# Generation: First 2 letters of device type (e.g., borderleaf -> bo)
# Parsing: Look up abbreviation to expand to full name (e.g., bo -> borderleaf)
#
# IMPORTANT: When adding new device types:
# 1. Add the 2-letter abbreviation here
# 2. The abbreviation MUST be the first 2 letters of the device type
# 3. This ensures parse_device_name() generates matching codes

DEVICE_ABBREVIATIONS = {
    # Fabric devices
    'sp': 'spine',
    'le': 'leaf',
    'bo': 'borderleaf',    # First 2 letters, NOT 'bl'
    'me': 'memleaf',

    # Edge/routing devices
    'fi': 'firewall',      # First 2 letters, NOT 'fw'
    'ga': 'gateway',       # First 2 letters, NOT 'gw'
    'ro': 'router',
    'co': 'core',
    'pe': 'pe',
    'ce': 'ce',
    'dc': 'dci',
    'rr': 'rr',

    # Endpoints
    'ho': 'host',
    'cl': 'client',
    'cu': 'customer',
    'oo': 'oob',

    # VeloCloud devices
    've': 'vce',           # VeloCloud Edge
    'vc': 'vcg',           # VeloCloud Gateway
    'vo': 'vco',           # VeloCloud Orchestrator

    # Provider/external
    'is': 'isp',
    'in': 'internet',

    # Legacy abbreviations (for parsing old bridges only)
    # These are NOT generated by nodebuilder, but may exist in old topologies
    'bl': 'borderleaf',    # Legacy: some old bridges use 'bl'
    'gw': 'gateway',       # Legacy: some old bridges use 'gw'
    'fw': 'firewall',      # Legacy: some old bridges use 'fw'
}


# =============================================================================
# BRIDGE NAME GENERATION
# =============================================================================

def parse_device_name(dev_name: str) -> Dict:
    """
    Parse a device name into a short code for bridge naming.

    Uses first 2 letters of device type + device number.
    This ensures consistency with DEVICE_ABBREVIATIONS for round-trip parsing.

    Examples:
        spine1 -> sp1
        leaf1 -> le1
        borderleaf1 -> bo1
        firewall1 -> fi1 (NOT fw1)
        gateway1 -> ga1 (NOT gw1)
        Ethernet3 -> 3 (just the number for ports)
        eth1 -> eth1 (Linux host interface, preserved)
        host1 -> ho1
        wan1 -> wa1 (VeloCloud WAN port)
        lan1 -> la1 (VeloCloud LAN port)

    Args:
        dev_name: Device or port name

    Returns:
        Dict with 'name' (original) and 'code' (short code)
    """
    alpha = ''
    numer = ''
    split_len = 2
    dev_dc = False
    dev_core = False
    tmp_dev_name = ""

    # Handle DC suffix (e.g., spine1-dc1)
    if '-dc' in dev_name.lower() and 'dci' not in dev_name.lower():
        _tmp = dev_name.split('-')
        tmp_dev_name = _tmp[0]
        if len(_tmp) > 1 and 'dc' in _tmp[1].lower():
            dev_dc = _tmp[1]
        for char in tmp_dev_name:
            if char.isalpha():
                alpha += char
            elif char.isdigit():
                numer += char
    # Handle CORE suffix (e.g., leaf1-core)
    elif '-core' in dev_name.lower():
        _tmp = dev_name.split('-')
        tmp_dev_name = _tmp[0]
        if len(_tmp) > 1:
            dev_core = _tmp[1]
        for char in tmp_dev_name:
            if char.isalpha():
                alpha += char
            elif char.isdigit():
                numer += char
    else:
        for char in dev_name:
            if char.isalpha():
                alpha += char
            elif char.isdigit():
                numer += char

    # For Ethernet ports, just use the number
    if 'ethernet' in dev_name.lower():
        dev_short = ''
    # For Linux eth ports (eth1, eth2), preserve 'eth' prefix
    elif dev_name.lower().startswith('eth') and len(alpha) == 3:
        dev_short = 'eth'
    else:
        dev_short = alpha[:split_len].lower()

    # Handle DC/CORE codes
    if dev_dc:
        dev_code = dev_dc.lower().replace('c', '')
    elif dev_core:
        dev_code = dev_core.lower().replace('ore', '')
    else:
        dev_code = ""

    return {
        'name': dev_name,
        'code': dev_short + numer + dev_code,
    }


def generate_bridge_name(
    device1: str,
    port1: str,
    device2: str,
    port2: str
) -> str:
    """
    Generate OVS bridge name following nodebuilder conventions.

    Format: {dev1_code}x{port1_code}-{dev2_code}x{port2_code}
    Example: le5x1-sp4x9 (leaf5 Ethernet1 to spine4 Ethernet9)

    The 'x' separator allows reliable parsing to extract device and port codes.

    Note: Device names are normalized to lowercase to ensure consistent
    bridge names regardless of input case (Spine1 vs spine1).

    Bridge names are limited to 15 characters (OVS/Linux interface limit).
    If the generated name exceeds this, it will be truncated with a hash suffix
    to maintain uniqueness.

    Args:
        device1: First device name
        port1: First port name
        device2: Second device name
        port2: Second port name

    Returns:
        Bridge name string (always lowercase, max 15 chars)
    """
    # Normalize to lowercase for consistent bridge names
    dev1_info = parse_device_name(device1.lower())
    port1_info = parse_device_name(port1.lower())
    dev2_info = parse_device_name(device2.lower())
    port2_info = parse_device_name(port2.lower())

    # Use 'x' as separator between device code and port code for better parsing
    # Format: {dev1_code}x{port1_code}-{dev2_code}x{port2_code}
    bridge_name = (
        f"{dev1_info['code']}x{port1_info['code']}-"
        f"{dev2_info['code']}x{port2_info['code']}"
    )

    # OVS/Linux has 15 char limit for interface names
    MAX_BRIDGE_LEN = 15
    if len(bridge_name) > MAX_BRIDGE_LEN:
        # Truncate and add hash suffix for uniqueness
        full_name = bridge_name
        hash_suffix = hashlib.md5(full_name.encode()).hexdigest()[:4]
        bridge_name = bridge_name[:MAX_BRIDGE_LEN - 5] + '-' + hash_suffix
        logger.debug(f"Bridge name truncated: {full_name} -> {bridge_name}")

    return bridge_name


def generate_interface_target_name(vm_name: str, suffix: str) -> str:
    """
    Generate a safe interface target name for libvirt VM definitions.

    Linux interface names are limited to 15 characters (IFNAMSIZ - 1).
    This function ensures the generated name fits within that limit.

    Format: {shortened_vm_name}_{suffix}
    If too long, truncates vm_name and adds hash for uniqueness.

    Examples:
        ('leaf1', 'mgmt') -> 'leaf1_mgmt' (10 chars, OK)
        ('orchestrator1', 'mgmt') -> 'orch1_m_a1b2' (12 chars, truncated)
        ('edge1', 'transport1') -> 'edge1_t1' (8 chars, OK)

    Args:
        vm_name: Name of the VM
        suffix: Interface suffix (e.g., 'mgmt', 'eth1', 'transport1')

    Returns:
        Interface target name (max 15 chars)
    """
    MAX_IFACE_LEN = 15

    # Shorten common suffixes
    suffix_map = {
        'mgmt': 'm',
        'management': 'm',
        'transport1': 't1',
        'transport2': 't2',
        'ethernet1': 'e1',
        'ethernet2': 'e2',
        'ethernet3': 'e3',
        'ethernet4': 'e4',
        'ethernet5': 'e5',
        'ethernet6': 'e6',
        'ethernet7': 'e7',
        'ethernet8': 'e8',
    }

    short_suffix = suffix_map.get(suffix.lower(), suffix.lower())

    # Try full name first
    full_name = f"{vm_name}_{short_suffix}"

    if len(full_name) <= MAX_IFACE_LEN:
        return full_name

    # Need to truncate - use first part of vm_name + hash + suffix
    # Format: {truncated_name}_{suffix}_{hash}
    # Reserve space for: underscore + suffix + underscore + 4-char hash
    hash_suffix = hashlib.md5(full_name.encode()).hexdigest()[:4]
    suffix_part = f"_{short_suffix}_{hash_suffix}"
    available_for_name = MAX_IFACE_LEN - len(suffix_part)

    if available_for_name < 2:
        # Extreme case - just use hash
        return f"vm_{hash_suffix}"

    truncated_name = vm_name[:available_for_name]
    result = f"{truncated_name}{suffix_part}"

    logger.debug(f"Interface target truncated: {full_name} -> {result}")
    return result


# =============================================================================
# BRIDGE NAME PARSING
# =============================================================================

def split_device_port(part: str) -> Tuple[str, str]:
    """
    Split a device+port string into (device_code, port_code).

    Handles multiple formats:
    1. 'x' separator: 'le5x1' -> ('le5', '1'), 'fi1xet1' -> ('fi1', 'et1')
    2. 'eth' prefix: 'client1eth1' -> ('client1', 'eth1')
    3. 'et' prefix: 'sp1et1' -> ('sp1', 'et1')
    4. Full names: 'leaf3Et3' -> ('leaf3', 'Et3')
    5. Legacy kvmbuilder: 'le11' -> ('le1', '1')

    Args:
        part: Combined device+port string

    Returns:
        Tuple of (device_code, port_code)
    """
    lower = part.lower()

    # Check for 'x' separator (nodebuilder format)
    # The separator 'x' should have a digit before it and:
    # - digit after (e.g., le5x1)
    # - 'e' after (e.g., fi1xet1 for eth port)
    # - 'w' after (e.g., ve1xwa1 for VeloCloud WAN)
    # - 'l' after (e.g., ve1xla1 for VeloCloud LAN)
    # - 't' after (e.g., vc1xtr1 for VeloCloud Gateway transport)
    for i, c in enumerate(lower):
        if c == 'x' and i > 0 and i < len(part) - 1:
            prev_char = lower[i - 1]
            next_char = lower[i + 1]
            if prev_char.isdigit() and (next_char.isdigit() or next_char in 'ewlt'):
                return part[:i], part[i + 1:]

    # Look for 'eth' (longer prefix, for Linux hosts)
    eth_idx = lower.find('eth')
    if eth_idx > 0:
        return part[:eth_idx], part[eth_idx:]

    # Look for 'et' (for Ethernet)
    et_idx = lower.find('et')
    if et_idx > 0:
        return part[:et_idx], part[et_idx:]

    # Legacy kvmbuilder format: {1-or-2-letter-prefix}{device-num}{port-num}
    # e.g., 'le11' = prefix 'le', device '1', port '1'
    # e.g., 'a11' = prefix 'a', device '1', port '1' (L4 topology: A1, P3, etc.)
    match = re.match(r'^([a-zA-Z]{1,2})(\d)(\d+)$', part)
    if match:
        prefix = match.group(1)
        device_num = match.group(2)
        port_num = match.group(3).lstrip('0') or '0'
        return f"{prefix}{device_num}", port_num

    # Fallback: return whole part as device with empty port
    return part, ""


def expand_device_code(code: str) -> str:
    """
    Expand abbreviated device code to full device name.

    Uses DEVICE_ABBREVIATIONS for lookup.

    Examples:
        le5 -> leaf5
        sp4 -> spine4
        fi1 -> firewall1
        bo1 -> borderleaf1

    Args:
        code: Abbreviated device code (e.g., 'le5')

    Returns:
        Full device name (e.g., 'leaf5')
    """
    if not code:
        return code

    # Extract prefix and number
    prefix = ''
    number = ''
    for char in code:
        if char.isalpha():
            prefix += char
        elif char.isdigit():
            number += char

    # Look up the full name
    prefix_lower = prefix.lower()
    if prefix_lower in DEVICE_ABBREVIATIONS:
        full_prefix = DEVICE_ABBREVIATIONS[prefix_lower]
        return f"{full_prefix}{number}"

    # If not found in mapping, return as-is (might already be full name)
    return code


def expand_port_code(code: str) -> str:
    """
    Expand abbreviated port code to full port name.

    Examples:
        1 -> Ethernet1
        et5 -> Ethernet5
        eth1 -> eth1 (Linux host interface, keep as-is)
        wa1 -> wan1 (VeloCloud WAN port)
        la1 -> lan1 (VeloCloud LAN port)

    Known limitation: 'et0' expands to 'Ethernet0' even if original was 'eth0'.
    This is because we can't distinguish between abbreviated Ethernet and
    abbreviated eth (Linux interface) in the bridge name.

    Args:
        code: Abbreviated port code

    Returns:
        Full port name
    """
    if not code:
        return code

    code_lower = code.lower()

    # Linux host interface - keep as-is
    if code_lower.startswith('eth'):
        return code

    # Full VeloCloud port names - keep as-is
    if code_lower.startswith('wan') or code_lower.startswith('lan'):
        return code

    # Abbreviated VeloCloud WAN port: wa1 -> wan1
    if code_lower.startswith('wa') and len(code) >= 3:
        number = ''.join(c for c in code if c.isdigit())
        if number:
            return f"wan{number}"
        return code

    # Abbreviated VeloCloud LAN port: la1 -> lan1
    if code_lower.startswith('la') and len(code) >= 3:
        number = ''.join(c for c in code if c.isdigit())
        if number:
            return f"lan{number}"
        return code

    # Abbreviated VeloCloud Gateway transport port: tr1 -> transport1
    if code_lower.startswith('tr') and len(code) >= 3:
        number = ''.join(c for c in code if c.isdigit())
        if number:
            return f"transport{number}"
        return code

    # Ethernet abbreviation: et5 -> Ethernet5
    if code_lower.startswith('et'):
        number = ''.join(c for c in code if c.isdigit())
        if number:
            return f"Ethernet{number}"
        return code

    # Just a number: 1 -> Ethernet1
    if code.isdigit():
        return f"Ethernet{code}"

    # Default: return as-is
    return code


def parse_bridge_name(bridge_name: str) -> Dict:
    """
    Parse bridge name to extract device/port information.

    This is the reverse of generate_bridge_name(), allowing display of
    friendly device and port names from the bridge name.

    Handles both formats:
    - Nodebuilder format: le5x1-sp4x9 (with 'x' separator)
    - Legacy kvmbuilder format: le11-sp41 (no separator)

    Args:
        bridge_name: OVS bridge name (e.g., 'le5x1-sp4x9')

    Returns:
        Dict with:
            source_device: Abbreviated source device code (e.g., 'le5')
            source_port: Abbreviated source port code (e.g., '1')
            source_device_name: Full source device name (e.g., 'leaf5')
            source_port_name: Full source port name (e.g., 'Ethernet1')
            target_device: Abbreviated target device code (e.g., 'sp4')
            target_port: Abbreviated target port code (e.g., '9')
            target_device_name: Full target device name (e.g., 'spine4')
            target_port_name: Full target port name (e.g., 'Ethernet9')
    """
    result = {
        "source_device": "",
        "source_port": "",
        "source_device_name": "",
        "source_port_name": "",
        "target_device": "",
        "target_port": "",
        "target_device_name": "",
        "target_port_name": ""
    }

    if '-' not in bridge_name:
        return result

    try:
        parts = bridge_name.split('-')
        if len(parts) >= 2:
            src = parts[0]
            tgt = parts[1]

            # Parse each part
            src_device, src_port = split_device_port(src)
            tgt_device, tgt_port = split_device_port(tgt)

            # Store abbreviated codes
            result["source_device"] = src_device
            result["source_port"] = src_port
            result["target_device"] = tgt_device
            result["target_port"] = tgt_port

            # Expand to full names for display
            result["source_device_name"] = expand_device_code(src_device)
            result["source_port_name"] = expand_port_code(src_port)
            result["target_device_name"] = expand_device_code(tgt_device)
            result["target_port_name"] = expand_port_code(tgt_port)

    except Exception as e:
        logger.warning(f"Parse error for bridge {bridge_name}: {e}")

    return result


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

def get_device_abbreviation(device_type: str) -> str:
    """
    Get the 2-letter abbreviation for a device type.

    This is the expected abbreviation that parse_device_name() will generate.

    Args:
        device_type: Device type name (e.g., 'borderleaf')

    Returns:
        2-letter abbreviation (e.g., 'bo')
    """
    return device_type[:2].lower()


def is_legacy_abbreviation(abbrev: str) -> bool:
    """
    Check if an abbreviation is a legacy format (not generated by nodebuilder).

    Legacy abbreviations like 'bl', 'gw', 'fw' are supported for parsing
    but are never generated by nodebuilder.

    Args:
        abbrev: 2-letter abbreviation

    Returns:
        True if this is a legacy abbreviation
    """
    legacy = {'bl', 'gw', 'fw'}
    return abbrev.lower() in legacy


def get_abbreviation_mapping() -> Dict[str, str]:
    """
    Get a copy of the device abbreviation mapping.

    Useful for other services that need to display device type mappings.

    Returns:
        Copy of DEVICE_ABBREVIATIONS dict
    """
    return DEVICE_ABBREVIATIONS.copy()
