#cloud-config
# Standard cloud-init format (no vyos_config_commands)

# Set hostname
hostname: firewall

# Set password and enable SSH password auth
password: vyos
chpasswd: { expire: False }
ssh_pwauth: True
