---
    lab_list:
      reset:
        description: "Reset All Devices to Base Lab (reset)"
      STP-Start:
        description: "Start STP LAB"
      STP-Troubleshooting:
        description: "Start TROUBLESHOOTING STP LAB"
      MLAG-Start:
        description: "Start MLAG BOWTIE LAB"
      MLAG-Troubleshooting:
        description: "Start TROUBLESHOOTING MLAG LAB"
      Routing-Start:
        description: "ROUTING BGP LAB"
      routing-troubleshooting:
        description: "Start TROUBLESHOOTING ROUTING BGP LAB"
      OSPF-Start:
        description: "Start ROUTING OSPF LAB"
      OSPF-MA-Start:
        description: "Start ROUTING MULTIAREA OSPF LAB"
      ACL-Start:
        description: "Start ACL LAB"
      ACL-Troubleshoot:
        description: "Start TROUBLESHOOTING ACL LAB"
      NSSA-Start:
        description: "Start BONUS LAB OSPF NSSA"
    labconfiglets:
      reset:
        spine1:
          - "spine1-base"
        spine2:
          - "spine2-base"
        spine3:
          - "spine3-base"
        spine4:
          - "spine4-base"
        leaf1:
          - "leaf1-base"
        leaf2:
          - "leaf2-base"
        leaf3:
          - "leaf3-base"
        leaf4:
          - "leaf4-base"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        borderleaf1:
          - "borderleaf1-base"
        borderleaf2:
          - "borderleaf2-base"
      STP-Start:
        spine1:
          - "spine1-base"
        spine2:
          - "spine2-base"
        spine3:
          - "spine3-base"
        spine4:
          - "spine4-base"
        leaf1:
          - "leaf1-base"
        leaf2:
          - "leaf2-base"
        leaf3:
          - "leaf3-base"
        leaf4:
          - "leaf4-base"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        borderleaf1:
          - "borderleaf1-base"
        borderleaf2:
          - "borderleaf2-base"
      STP-Troubleshooting:
        spine1:
          - "spine1-base"
          - "TroubleSTP-Start-Spine1"
        spine2:
          - "spine2-base"
          - "TroubleSTP-Start-Spine2"
        spine3:
          - "spine3-base"
          - "TroubleSTP-Start-Spine3"
        spine4:
          - "spine4-base"
          - "TroubleSTP-Start-Spine4"
        leaf1:
          - "leaf1-base"
          - "TroubleSTP-Start-Leaf1"
        leaf2:
          - "leaf2-base"
          - "TroubleSTP-Start-Leaf2"
        leaf3:
          - "leaf3-base"
          - "TroubleSTP-Start-Leaf3"
        leaf4:
          - "leaf4-base"
          - "TroubleSTP-Start-Leaf4"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        borderleaf1:
          - "borderleaf1-base"
        borderleaf2:
          - "borderleaf2-base"
      MLAG-Start:
        spine1:
          - "spine1-base"
        spine2:
          - "spine2-base"
        spine3:
          - "spine3-base"
        spine4:
          - "spine4-base"
        leaf1:
          - "leaf1-base"
        leaf2:
          - "leaf2-base"
        leaf3:
          - "leaf3-base"
        leaf4:
          - "leaf4-base"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        borderleaf1:
          - "borderleaf1-base"
        borderleaf2:
          - "borderleaf2-base"
      MLAG-Troubleshooting:
        spine1:
          - "spine1-base"
          - "TroubleMLAG-Spine1"
        spine2:
          - "spine2-base"
          - "TroubleMLAG-Spine2"
        spine3:
          - "spine3-base"
        spine4:
          - "spine4-base"
        leaf1:
          - "leaf1-base"
          - "TroubleMLAG-Leaf1"
        leaf2:
          - "leaf2-base"
          - "TroubleMLAG-Leaf2"
        leaf3:
          - "leaf3-base"
          - "TroubleMLAG-Leaf3"
        leaf4:
          - "leaf4-base"
          - "TroubleMLAG-Leaf4"
        host1:
          - "host1-base"
          - "TroubleMLAG-Host1"
        host2:
          - "host2-base"
          - "TroubleMLAG-Host2"
        host3:
          - "host3-base"
          - "TroubleMLAG-Host3"
        host4:
          - "host4-base"
          - "TroubleMLAG-Host4"
        borderleaf1:
          - "borderleaf1-base"
        borderleaf2:
          - "borderleaf2-base"
      Routing-Start:
        spine1:
          - "spine1-base"
        spine2:
          - "spine2-base"
        spine3:
          - "spine3-base"
        spine4:
          - "spine4-base"
        leaf1:
          - "leaf1-base"
        leaf2:
          - "leaf2-base"
        leaf3:
          - "leaf3-base"
        leaf4:
          - "leaf4-base"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        borderleaf1:
          - "borderleaf1-base"
        borderleaf2:
          - "borderleaf2-base"
      OSPF-Start:
        spine1:
          - "spine1-base"
        spine2:
          - "spine2-base"
        spine3:
          - "spine3-base"
        spine4:
          - "spine4-base"
        leaf1:
          - "leaf1-base"
        leaf2:
          - "leaf2-base"
        leaf3:
          - "leaf3-base"
        leaf4:
          - "leaf4-base"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        borderleaf1:
          - "borderleaf1-base"
        borderleaf2:
          - "borderleaf2-base"
      NSSA-Start:
        spine1:
          - "spine1-base"
          - "NSSA-Start-Spine1"
        spine2:
          - "spine2-base"
          - "NSSA-Start-Spine2"
        spine3:
          - "spine3-base"
          - "NSSA-Start-Spine3"
        spine4:
          - "spine4-base"
          - "NSSA-Start-Spine4"
        leaf1:
          - "leaf1-base"
          - "NSSA-Start-Leaf1"
        leaf2:
          - "leaf2-base"
          - "NSSA-Start-Leaf2"
        leaf3:
          - "leaf3-base"
          - "NSSA-Start-Leaf3"
        leaf4:
          - "leaf4-base"
          - "NSSA-Start-Leaf4"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        borderleaf1:
          - "borderleaf1-base"
          - "NSSA-Start-BorderLeaf1"
        borderleaf2:
          - "borderleaf2-base"
          - "NSSA-Start-BorderLeaf2"
      ACL-Start:
        spine1:
          - "spine1-base"
          - "ACL-Start-Spine1"
        spine2:
          - "spine2-base"
          - "ACL-Start-Spine2"
        spine3:
          - "spine3-base"
          - "ACL-Start-Spine3"
        spine4:
          - "spine4-base"
          - "ACL-Start-Spine4"
        leaf1:
          - "leaf1-base"
          - "ACL-Start-Leaf1"
        leaf2:
          - "leaf2-base"
          - "ACL-Start-Leaf2"
        leaf3:
          - "leaf3-base"
          - "ACL-Start-Leaf3"
        leaf4:
          - "leaf4-base"
          - "ACL-Start-Leaf4"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        borderleaf1:
          - "borderleaf1-base"
          - "ACL-Start-BorderLeaf1"
        borderleaf2:
          - "borderleaf2-base"
          - "ACL-Start-BorderLeaf2"
      ACL-Troubleshoot:
        spine1:
          - "spine1-base"
          - "TroubleACL-Start-Spine1"
        spine2:
          - "spine2-base"
          - "TroubleACL-Start-Spine2"
        spine3:
          - "spine3-base"
          - "TroubleACL-Start-Spine3"
        spine4:
          - "spine4-base"
          - "TroubleACL-Start-Spine4"
        leaf1:
          - "leaf1-base"
          - "TroubleACL-Start-Leaf1"
        leaf2:
          - "leaf2-base"
          - "TroubleACL-Start-Leaf2"
        leaf3:
          - "leaf3-base"
          - "TroubleACL-Start-Leaf3"
        leaf4:
          - "leaf4-base"
          - "TroubleACL-Start-Leaf4"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        borderleaf1:
          - "borderleaf1-base"
          - "TroubleACL-Start-BorderLeaf1"
        borderleaf2:
          - "borderleaf2-base"
          - "TroubleACL-Start-BorderLeaf2"
      routing-troubleshooting:
        spine1:
          - "spine1-base"
          - "TroubleBGP-Spine1"
        spine2:
          - "spine2-base"
          - "TroubleBGP-Spine2"
        spine3:
          - "spine3-base"
          - "TroubleBGP-Spine3"
        spine4:
          - "spine4-base"
          - "TroubleBGP-Spine4"
        leaf1:
          - "leaf1-base"
          - "TroubleBGP-Start-Leaf1"
        leaf2:
          - "leaf2-base"
          - "TroubleBGP-Start-Leaf2"
        leaf3:
          - "leaf3-base"
          - "TroubleBGP-Start-Leaf3"
        leaf4:
          - "leaf4-base"
          - "TroubleBGP-Leaf4"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        borderleaf1:
          - "borderleaf1-base"
          - "TroubleBGP-BorderLeaf1"
        borderleaf2:
          - "borderleaf2-base"
          - "TroubleBGP-BorderLeaf2"
      OSPF-MA-Start:
        spine1:
          - "spine1-base"
          - "Spine1-OSPFMultiArea-Start"
        spine2:
          - "spine2-base"
          - "Spine2-OSPFMultiArea-Start"
        spine3:
          - "spine3-base"
          - "Spine3-OSPFMultiArea-Start"
        spine4:
          - "spine4-base"
          - "Spine4-OSPFMultiArea-Start"
        leaf1:
          - "leaf1-base"
          - "Leaf1-OSPFMultiaArea-Start"
        leaf2:
          - "leaf2-base"
          - "Leaf2-OSPFMultiaArea-Start"
        leaf3:
          - "leaf3-base"
          - "Leaf3-OSPFMultiaArea-Start"
        leaf4:
          - "leaf4-base"
          - "Leaf4-OSPFMultiaArea-Start"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        borderleaf1:
          - "borderleaf1-base"
          - "BorderLeaf1-OSPFMultiArea-Start"
        borderleaf2:
          - "borderleaf2-base"
          - "BorderLeaf2-OSPFMultiArea-Start"