---
    lab_list:
      reset:
        description: "Reset All Devices to Base Lab (reset)"
    labconfiglets:
      reset:
        spine1:
          - "spine1-base"
        spine2:
          - "spine2-base"
        spine3:
          - "spine3-base"
        spine4:
          - "spine4-base"
        leaf1:
          - "leaf1-base"
        leaf2:
          - "leaf2-base"
        leaf3:
          - "leaf3-base"
        leaf4:
          - "leaf4-base"
        leaf5:
          - "leaf5-base"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        host4:
          - "host4-base"
        host5:
          - "host5-base"
        memleaf1:
          - "memleaf1-base"
        memleaf2:
          - "memleaf2-base"
        router1:
          - "router-1-base"
        router2: 
          - "router-2-base"
    
