---
    lab_list:
      reset:
        description: "Reset All Devices to Base Lab (reset)"
    labconfiglets:
      reset:
        Wan-1:
          - "Wan-1-BASE"
        Router-1:
          - "Router-1-BASE"
        Router-2:
          - "Router-2-BASE"
        Core-1:
          - "Core-1-BASE"
        Core-1:
          - "Core-2-BASE"
        Access-1:
          - "Access-1-BADE"
        Access-2:
          - "Access-2-BASE"

