---
    lab_list:
      reset:
        description: "Reset All Devices to Base Lab (reset)"
    labconfiglets:
      reset:
        Wan-1:
          - "Wan-1-BASE"
        Router-1:
          - "Router-1-BASE"
        Router-2:
          - "Router-2-BASE"
        Core-1:
          - "Core-1-BASE"
        Core-2:
          - "Core-2-BASE"
        Access-1:
          - "Access-1-BASE"
        Access-2:
          - "Access-2-BASE"
        host-1:
          - "host-1-BASE"
        host-11:
          - "host-11-BASE"
        host-12:
          - "host-12-BASE"
          



