---
    lab_list:
      reset:
        description: "Reset All Devices to Base Lab (reset)"
    labconfiglets:
      reset:
        spine1:
          - "spine1-base"
        spine2:
          - "spine2-base"
        leaf1:
          - "leaf1-base"
        leaf2:
          - "leaf2-base"
        leaf3:
          - "leaf3-base"
        leaf4:
          - "leaf4-base"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        host3:
          - "host3-base"
        borderleaf1:
          - "borderleaf1-base"