"""
Unit tests for bridge name parsing in captureservice.

Tests cover:
- Nodebuilder format parsing (with 'x' separator)
- Legacy kvmbuilder format parsing
- Device code expansion
- Port code expansion
- VeloCloud port handling
- Edge cases and error handling

These tests ensure that bridge names generated by nodebuilder can be
correctly parsed back to device/port names for the capture panel and
link impairments feature.
"""

import pytest
from unittest.mock import Mock, patch, MagicMock


class MockCaptureManager:
    """
    Mock CaptureManager with just the bridge parsing methods.
    Extracted from capture_service.py for isolated testing.
    """

    # Device abbreviations - must match nodebuilder's parse_device_name()
    DEVICE_ABBREVIATIONS = {
        'sp': 'spine',
        'le': 'leaf',
        'bo': 'borderleaf',
        'ho': 'host',
        'fi': 'firewall',
        've': 'vce',
        'vc': 'vcg',
        'vo': 'vco',
        'cl': 'client',
        'co': 'core',
        'pe': 'pe',
        'ce': 'ce',
        'dc': 'dci',
        'rr': 'rr',
        'ga': 'gateway',
        'ro': 'router',
        'is': 'isp',
        'in': 'internet',
        'me': 'memleaf',
        'cu': 'customer',
        'oo': 'oob',
        # Legacy mappings
        'bl': 'borderleaf',
        'gw': 'gateway',
    }

    def _parse_bridge_name(self, bridge_name: str) -> dict:
        """Parse bridge name to extract device/port info."""
        import re

        result = {
            "source_device": "",
            "source_port": "",
            "source_device_name": "",
            "source_port_name": "",
            "target_device": "",
            "target_port": "",
            "target_device_name": "",
            "target_port_name": ""
        }

        if '-' not in bridge_name:
            return result

        try:
            parts = bridge_name.split('-')
            if len(parts) >= 2:
                src = parts[0]
                tgt = parts[1]

                src_device, src_port = self._split_device_port(src)
                tgt_device, tgt_port = self._split_device_port(tgt)

                result["source_device"] = src_device
                result["source_port"] = src_port
                result["target_device"] = tgt_device
                result["target_port"] = tgt_port

                result["source_device_name"] = self._expand_device_code(src_device)
                result["source_port_name"] = self._expand_port_code(src_port)
                result["target_device_name"] = self._expand_device_code(tgt_device)
                result["target_port_name"] = self._expand_port_code(tgt_port)

        except Exception:
            pass

        return result

    def _split_device_port(self, part: str) -> tuple:
        """Split a device+port string into (device, port)."""
        import re
        lower = part.lower()

        # Check for 'x' separator (nodebuilder format)
        # Valid next chars: digit, 'e' (eth), 'w' (wan), 'l' (lan)
        for i, c in enumerate(lower):
            if c == 'x' and i > 0 and i < len(part) - 1:
                prev_char = lower[i - 1]
                next_char = lower[i + 1]
                if prev_char.isdigit() and (next_char.isdigit() or next_char in 'ewl'):
                    return part[:i], part[i + 1:]

        # Look for 'eth' (for Linux hosts)
        eth_idx = lower.find('eth')
        if eth_idx > 0:
            return part[:eth_idx], part[eth_idx:]

        # Look for 'et' (for Ethernet)
        et_idx = lower.find('et')
        if et_idx > 0:
            return part[:et_idx], part[et_idx:]

        # Legacy kvmbuilder format
        match = re.match(r'^([a-zA-Z]{2})(\d)(\d+)$', part)
        if match:
            prefix = match.group(1)
            device_num = match.group(2)
            port_num = match.group(3).lstrip('0') or '0'
            return f"{prefix}{device_num}", port_num

        return part, ""

    def _expand_device_code(self, code: str) -> str:
        """Expand abbreviated device code to full device name."""
        if not code:
            return code

        prefix = ''
        number = ''
        for char in code:
            if char.isalpha():
                prefix += char
            elif char.isdigit():
                number += char

        prefix_lower = prefix.lower()
        if prefix_lower in self.DEVICE_ABBREVIATIONS:
            full_prefix = self.DEVICE_ABBREVIATIONS[prefix_lower]
            return f"{full_prefix}{number}"

        return code

    def _expand_port_code(self, code: str) -> str:
        """Expand abbreviated port code to full port name."""
        if not code:
            return code

        code_lower = code.lower()

        # Linux host interface - keep as-is
        if code_lower.startswith('eth'):
            return code

        # Full VeloCloud port names - keep as-is
        if code_lower.startswith('wan') or code_lower.startswith('lan'):
            return code

        # Abbreviated VeloCloud WAN port: wa1 -> wan1
        if code_lower.startswith('wa') and len(code) >= 3:
            number = ''.join(c for c in code if c.isdigit())
            if number:
                return f"wan{number}"
            return code

        # Abbreviated VeloCloud LAN port: la1 -> lan1
        if code_lower.startswith('la') and len(code) >= 3:
            number = ''.join(c for c in code if c.isdigit())
            if number:
                return f"lan{number}"
            return code

        # Ethernet abbreviation: et5 -> Ethernet5
        if code_lower.startswith('et'):
            number = ''.join(c for c in code if c.isdigit())
            if number:
                return f"Ethernet{number}"
            return code

        # Pure numeric: 5 -> Ethernet5
        if code.isdigit():
            return f"Ethernet{code}"

        return code


class TestDeviceAbbreviations:
    """Test that device abbreviations match nodebuilder's conventions."""

    def test_abbreviations_use_first_two_letters(self):
        """Verify abbreviations use first 2 letters of device type."""
        manager = MockCaptureManager()

        # Key mappings that must match nodebuilder
        assert manager.DEVICE_ABBREVIATIONS['sp'] == 'spine'
        assert manager.DEVICE_ABBREVIATIONS['le'] == 'leaf'
        assert manager.DEVICE_ABBREVIATIONS['bo'] == 'borderleaf'  # 'bo' not 'bl'
        assert manager.DEVICE_ABBREVIATIONS['ho'] == 'host'
        assert manager.DEVICE_ABBREVIATIONS['fi'] == 'firewall'    # 'fi' not 'fw'
        assert manager.DEVICE_ABBREVIATIONS['ga'] == 'gateway'     # 'ga' not 'gw'

    def test_velocloud_abbreviations(self):
        """Test VeloCloud device abbreviations."""
        manager = MockCaptureManager()

        assert manager.DEVICE_ABBREVIATIONS['ve'] == 'vce'
        assert manager.DEVICE_ABBREVIATIONS['vc'] == 'vcg'
        assert manager.DEVICE_ABBREVIATIONS['vo'] == 'vco'

    def test_legacy_abbreviations_supported(self):
        """Test legacy kvmbuilder abbreviations for backwards compatibility."""
        manager = MockCaptureManager()

        # Legacy mappings should still work
        assert manager.DEVICE_ABBREVIATIONS['bl'] == 'borderleaf'
        assert manager.DEVICE_ABBREVIATIONS['gw'] == 'gateway'


class TestExpandDeviceCode:
    """Test device code expansion."""

    @pytest.fixture
    def manager(self):
        return MockCaptureManager()

    def test_spine_expansion(self, manager):
        """Test spine device code expansion."""
        assert manager._expand_device_code('sp1') == 'spine1'
        assert manager._expand_device_code('sp4') == 'spine4'
        assert manager._expand_device_code('sp12') == 'spine12'

    def test_leaf_expansion(self, manager):
        """Test leaf device code expansion."""
        assert manager._expand_device_code('le1') == 'leaf1'
        assert manager._expand_device_code('le5') == 'leaf5'

    def test_firewall_expansion(self, manager):
        """Test firewall device code expansion (fi, not fw)."""
        assert manager._expand_device_code('fi1') == 'firewall1'
        assert manager._expand_device_code('fi2') == 'firewall2'

    def test_borderleaf_expansion(self, manager):
        """Test borderleaf device code expansion."""
        assert manager._expand_device_code('bo1') == 'borderleaf1'
        # Legacy format also works
        assert manager._expand_device_code('bl1') == 'borderleaf1'

    def test_gateway_expansion(self, manager):
        """Test gateway device code expansion (ga, not gw)."""
        assert manager._expand_device_code('ga1') == 'gateway1'
        # Legacy format also works
        assert manager._expand_device_code('gw1') == 'gateway1'

    def test_velocloud_expansion(self, manager):
        """Test VeloCloud device code expansion."""
        assert manager._expand_device_code('ve1') == 'vce1'
        assert manager._expand_device_code('vc1') == 'vcg1'
        assert manager._expand_device_code('vo1') == 'vco1'

    def test_empty_code(self, manager):
        """Test empty code returns empty string."""
        assert manager._expand_device_code('') == ''

    def test_unknown_code_passthrough(self, manager):
        """Test unknown codes are passed through unchanged."""
        assert manager._expand_device_code('xx1') == 'xx1'
        assert manager._expand_device_code('leaf5') == 'leaf5'


class TestExpandPortCode:
    """Test port code expansion."""

    @pytest.fixture
    def manager(self):
        return MockCaptureManager()

    def test_numeric_to_ethernet(self, manager):
        """Test pure numeric codes become Ethernet ports."""
        assert manager._expand_port_code('1') == 'Ethernet1'
        assert manager._expand_port_code('5') == 'Ethernet5'
        assert manager._expand_port_code('12') == 'Ethernet12'

    def test_et_prefix_to_ethernet(self, manager):
        """Test 'et' prefix codes become Ethernet ports."""
        assert manager._expand_port_code('et1') == 'Ethernet1'
        assert manager._expand_port_code('et5') == 'Ethernet5'
        assert manager._expand_port_code('Et3') == 'Ethernet3'

    def test_eth_prefix_unchanged(self, manager):
        """Test 'eth' prefix (Linux host) stays unchanged."""
        assert manager._expand_port_code('eth0') == 'eth0'
        assert manager._expand_port_code('eth1') == 'eth1'

    def test_velocloud_wan_expansion(self, manager):
        """Test VeloCloud WAN port expansion."""
        assert manager._expand_port_code('wa1') == 'wan1'
        assert manager._expand_port_code('wa2') == 'wan2'
        # Full name unchanged
        assert manager._expand_port_code('wan1') == 'wan1'

    def test_velocloud_lan_expansion(self, manager):
        """Test VeloCloud LAN port expansion."""
        assert manager._expand_port_code('la1') == 'lan1'
        assert manager._expand_port_code('la2') == 'lan2'
        # Full name unchanged
        assert manager._expand_port_code('lan1') == 'lan1'

    def test_empty_code(self, manager):
        """Test empty code returns empty string."""
        assert manager._expand_port_code('') == ''


class TestSplitDevicePort:
    """Test splitting device+port strings."""

    @pytest.fixture
    def manager(self):
        return MockCaptureManager()

    def test_nodebuilder_x_separator(self, manager):
        """Test nodebuilder format with 'x' separator."""
        assert manager._split_device_port('le5x1') == ('le5', '1')
        assert manager._split_device_port('sp4x9') == ('sp4', '9')
        assert manager._split_device_port('fi1x3') == ('fi1', '3')

    def test_nodebuilder_x_with_et_port(self, manager):
        """Test nodebuilder format with 'et' port prefix."""
        assert manager._split_device_port('fi1xet1') == ('fi1', 'et1')
        assert manager._split_device_port('ho1xeth0') == ('ho1', 'eth0')

    def test_eth_prefix_split(self, manager):
        """Test splitting on 'eth' prefix."""
        assert manager._split_device_port('client1eth1') == ('client1', 'eth1')
        assert manager._split_device_port('host1eth0') == ('host1', 'eth0')

    def test_et_prefix_split(self, manager):
        """Test splitting on 'et' prefix."""
        assert manager._split_device_port('sp1et1') == ('sp1', 'et1')
        assert manager._split_device_port('leaf3Et3') == ('leaf3', 'Et3')

    def test_legacy_kvmbuilder_format(self, manager):
        """Test legacy kvmbuilder format parsing."""
        # le11 = leaf1, port 1
        assert manager._split_device_port('le11') == ('le1', '1')
        # sp23 = spine2, port 3
        assert manager._split_device_port('sp23') == ('sp2', '3')
        # le14 = leaf1, port 4
        assert manager._split_device_port('le14') == ('le1', '4')

    def test_unknown_format_passthrough(self, manager):
        """Test unknown format returns whole string as device."""
        assert manager._split_device_port('unknown') == ('unknown', '')


class TestParseBridgeName:
    """Test full bridge name parsing."""

    @pytest.fixture
    def manager(self):
        return MockCaptureManager()

    def test_nodebuilder_basic_format(self, manager):
        """Test parsing nodebuilder format bridge names."""
        result = manager._parse_bridge_name('le5x1-sp4x9')

        assert result['source_device'] == 'le5'
        assert result['source_port'] == '1'
        assert result['source_device_name'] == 'leaf5'
        assert result['source_port_name'] == 'Ethernet1'

        assert result['target_device'] == 'sp4'
        assert result['target_port'] == '9'
        assert result['target_device_name'] == 'spine4'
        assert result['target_port_name'] == 'Ethernet9'

    def test_firewall_to_borderleaf(self, manager):
        """Test firewall to borderleaf connection parsing."""
        result = manager._parse_bridge_name('fi1x3-bo1x7')

        assert result['source_device_name'] == 'firewall1'
        assert result['source_port_name'] == 'Ethernet3'
        assert result['target_device_name'] == 'borderleaf1'
        assert result['target_port_name'] == 'Ethernet7'

    def test_host_with_eth_interface_preserved(self, manager):
        """Test host with Linux eth interface (if preserved in bridge name).

        This tests parsing bridges where 'eth0' is preserved (e.g., legacy format).
        """
        result = manager._parse_bridge_name('ho1xeth0-le1x5')

        assert result['source_device_name'] == 'host1'
        assert result['source_port_name'] == 'eth0'
        assert result['target_device_name'] == 'leaf1'
        assert result['target_port_name'] == 'Ethernet5'

    def test_host_with_eth_abbreviated(self, manager):
        """Test host with abbreviated eth interface (nodebuilder format).

        Nodebuilder abbreviates 'eth0' to 'et0' using parse_device_name.
        When parsing, 'et0' expands to 'Ethernet0' (known limitation).
        """
        result = manager._parse_bridge_name('ho1xet0-le1x5')

        assert result['source_device_name'] == 'host1'
        # 'et0' -> 'Ethernet0' (can't distinguish from Ethernet abbreviation)
        assert result['source_port_name'] == 'Ethernet0'
        assert result['target_device_name'] == 'leaf1'
        assert result['target_port_name'] == 'Ethernet5'

    def test_velocloud_edge_wan_connection(self, manager):
        """Test VeloCloud Edge WAN port connection."""
        result = manager._parse_bridge_name('ve1xwa1-ro1x1')

        assert result['source_device_name'] == 'vce1'
        assert result['source_port_name'] == 'wan1'
        assert result['target_device_name'] == 'router1'
        assert result['target_port_name'] == 'Ethernet1'

    def test_velocloud_edge_lan_connection(self, manager):
        """Test VeloCloud Edge LAN port connection."""
        result = manager._parse_bridge_name('ve1xla1-le1x8')

        assert result['source_device_name'] == 'vce1'
        assert result['source_port_name'] == 'lan1'
        assert result['target_device_name'] == 'leaf1'
        assert result['target_port_name'] == 'Ethernet8'

    def test_legacy_kvmbuilder_format(self, manager):
        """Test parsing legacy kvmbuilder format bridge names."""
        result = manager._parse_bridge_name('le11-sp13')

        assert result['source_device_name'] == 'leaf1'
        assert result['source_port_name'] == 'Ethernet1'
        assert result['target_device_name'] == 'spine1'
        assert result['target_port_name'] == 'Ethernet3'

    def test_full_name_format(self, manager):
        """Test parsing full name format bridge names."""
        result = manager._parse_bridge_name('leaf3Et3-leaf1Et3')

        assert result['source_device_name'] == 'leaf3'
        assert result['source_port_name'] == 'Ethernet3'
        assert result['target_device_name'] == 'leaf1'
        assert result['target_port_name'] == 'Ethernet3'

    def test_no_separator_returns_empty(self, manager):
        """Test bridge name without separator returns empty fields."""
        result = manager._parse_bridge_name('noseparator')

        assert result['source_device'] == ''
        assert result['source_port'] == ''
        assert result['source_device_name'] == ''

    def test_empty_string(self, manager):
        """Test empty string returns empty fields."""
        result = manager._parse_bridge_name('')

        assert result['source_device'] == ''
        assert result['target_device'] == ''


class TestBridgeNameRoundTrip:
    """
    Test that bridge names generated by nodebuilder can be
    correctly parsed back to the original device/port names.

    These tests verify the integration between nodebuilder's
    generate_bridge_name() and captureservice's _parse_bridge_name().
    """

    @pytest.fixture
    def manager(self):
        return MockCaptureManager()

    def test_veos_to_veos_roundtrip(self, manager):
        """Test vEOS to vEOS connection roundtrip."""
        # Bridge: le1x1-sp1x1 (leaf1:Ethernet1 <-> spine1:Ethernet1)
        result = manager._parse_bridge_name('le1x1-sp1x1')

        assert result['source_device_name'] == 'leaf1'
        assert result['source_port_name'] == 'Ethernet1'
        assert result['target_device_name'] == 'spine1'
        assert result['target_port_name'] == 'Ethernet1'

    def test_firewall_roundtrip(self, manager):
        """Test firewall connection roundtrip (fi prefix, not fw)."""
        # Bridge: fi1x1-bo1x5 (firewall1:Ethernet1 <-> borderleaf1:Ethernet5)
        result = manager._parse_bridge_name('fi1x1-bo1x5')

        assert result['source_device_name'] == 'firewall1'
        assert result['source_port_name'] == 'Ethernet1'
        assert result['target_device_name'] == 'borderleaf1'
        assert result['target_port_name'] == 'Ethernet5'

    def test_host_roundtrip(self, manager):
        """Test Linux host connection roundtrip."""
        # Bridge: ho1xeth0-le1x10 (host1:eth0 <-> leaf1:Ethernet10)
        result = manager._parse_bridge_name('ho1xeth0-le1x10')

        assert result['source_device_name'] == 'host1'
        assert result['source_port_name'] == 'eth0'
        assert result['target_device_name'] == 'leaf1'
        assert result['target_port_name'] == 'Ethernet10'

    def test_velocloud_roundtrip(self, manager):
        """Test VeloCloud device connection roundtrip."""
        # VeloCloud Edge with WAN port
        result = manager._parse_bridge_name('ve1xwa1-is1x1')

        assert result['source_device_name'] == 'vce1'
        assert result['source_port_name'] == 'wan1'
        assert result['target_device_name'] == 'isp1'
        assert result['target_port_name'] == 'Ethernet1'

    def test_high_port_numbers(self, manager):
        """Test connections with high port numbers."""
        # Leaf with Ethernet12 to spine with Ethernet24
        result = manager._parse_bridge_name('le1x12-sp1x24')

        assert result['source_port_name'] == 'Ethernet12'
        assert result['target_port_name'] == 'Ethernet24'

    def test_high_device_numbers(self, manager):
        """Test devices with high numbers."""
        # leaf15 to spine8
        result = manager._parse_bridge_name('le15x1-sp8x1')

        assert result['source_device_name'] == 'leaf15'
        assert result['target_device_name'] == 'spine8'


class TestLinkImpairments:
    """
    Test bridge parsing in the context of link impairments.

    Link impairments (latency, jitter, loss, duplication, corruption)
    use the same bridge parsing code to identify which OVS bridge
    to apply tc netem rules to.
    """

    @pytest.fixture
    def manager(self):
        return MockCaptureManager()

    def test_impairment_bridge_identification(self, manager):
        """Test that bridges can be identified for impairment."""
        # Given a user-added leaf5 connected to spine4
        bridge = 'le5x1-sp4x9'
        result = manager._parse_bridge_name(bridge)

        # The parsing should correctly identify the link endpoints
        assert result['source_device_name'] == 'leaf5'
        assert result['target_device_name'] == 'spine4'

        # This allows the UI to show the correct device names
        # when applying latency/jitter/loss to the link

    def test_firewall_impairment_bridge(self, manager):
        """Test firewall link can receive impairments."""
        bridge = 'fi1x1-le1x5'
        result = manager._parse_bridge_name(bridge)

        assert result['source_device_name'] == 'firewall1'
        assert result['target_device_name'] == 'leaf1'

    def test_host_impairment_bridge(self, manager):
        """Test host link can receive impairments."""
        bridge = 'ho1xeth0-le1x10'
        result = manager._parse_bridge_name(bridge)

        assert result['source_device_name'] == 'host1'
        assert result['target_device_name'] == 'leaf1'
