---
    lab_list:
      reset:
        additional_commands: 
          - "bash /home/arista/Broadcaster/pushHostDefaultConfig.sh"
        description: "Reset All Devices to Base Lab (reset)"
      vxlan:
        description: "VXLAN Lab (vxlan)"
      l2evpn:
        description: "L2-EVPN Lab (l2evpn)"
      l3evpn:
        description: "L3-EVPN Lab (l3evpn)"
      aamh:
        description: "Active-Active Multi Homing lab (aamh)"
      pim:
        description: "PIM Lab (pim)"
    labconfiglets:
      reset:
        spine1:
          - "spine1-base"
        spine2:
          - "spine2-base"
        spine3:
          - "spine3-base"
        leaf1:
          - "leaf1-base"
        leaf2:
          - "leaf2-base"
        leaf3:
          - "leaf3-base"
        leaf4:
          - "leaf4-base"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        borderleaf1:
          - "borderleaf1-base"
        borderleaf2:
          - "borderleaf2-base"
      vxlan:
        spine1:
          - "spine1-base"
          - "Spine-1-VXLAN-Begin"
        spine2:
          - "spine2-base"
          - "Spine-2-VXLAN-Begin"
        spine3:
          - "spine3-base"
          - "Spine-3-VXLAN-Begin"
        leaf1:
          - "leaf1-base"
          - "Leaf-1-VXLAN-Begin"
        leaf2:
          - "leaf2-base"
          - "Leaf-1-VXLAN-Begin"
        leaf3:
          - "leaf3-base"
          - "leaf-3-VXLAN-Begin"
        leaf4:
          - "leaf4-base"
          - "leaf-3-VXLAN-Begin"
        host1:
          - "host1-base"
          - "Host-1-VXLAN-Begin"
        host2:
          - "host2-base"
          - "Host-2-VXLAN-Begin"
        borderleaf1:
          - "borderleaf1-base"
          - "Borderleaf-1-VXLAN-Begin"
        borderleaf2:
          - "borderleaf2-base"
          - "Borderleaf-2-VXLAN-Begin"
      l2evpn:
        spine1:
          - "spine1-base"
          - "Spine-1-L2EVPN-Begin"
        spine2:
          - "spine2-base"
          - "Spine-2-L2EVPN-Begin"
        spine3:
          - "spine3-base"
          - "Spine-3-L2EVPN-Begin"
        leaf1:
          - "leaf1-base"
          - "Leaf-1-L2EVPN-Begin"
        leaf2:
          - "leaf2-base"
          - "Leaf-2-L2EVPN-Begin"
        leaf3:
          - "leaf3-base"
          - "Leaf-3-L2EVPN-Begin"
        leaf4:
          - "leaf4-base"
          - "Leaf-4-L2EVPN-Begin"
        host1:
          - "host1-base"
          - "Host-1-L2EVPN-Begin"
        host2:
          - "host2-base"
          - "Host-2-L2EVPN-Begin"
        borderleaf1:
          - "borderleaf1-base"
          - "Borderleaf-1-L2EVPN-Begin"
        borderleaf2:
          - "borderleaf2-base"
          - "Borderleaf-2-L2EVPN-Begin"
      l3evpn:
        spine1:
          - "spine1-base"
          - "Spine-1-L3EVPN-Begin"
        spine2:
          - "spine2-base"
          - "Spine-2-L3EVPN-Begin"
        spine3:
          - "spine3-base"
          - "Spine-3-L3EVPN-Begin"
        leaf1:
          - "leaf1-base"
          - "Leaf-1-L3EVPN-Begin"
        leaf2:
          - "leaf2-base"
          - "Leaf-2-L3EVPN-Begin"
        leaf3:
          - "leaf3-base"
          - "Leaf-3-L3EVPN-Begin"
        leaf4:
          - "leaf4-base"
          - "Leaf-4-L3EVPN-Begin"
        host1:
          - "host1-base"
          - "Host-1-L3EVPN-Begin"
        host2:
          - "host2-base"
          - "Host-2-L3EVPN-Begin"
        borderleaf1:
          - "borderleaf1-base"
          - "Borderleaf-1-L3EVPN-Begin"
        borderleaf2:
          - "borderleaf2-base"
          - "Borderleaf-2-L3EVPN-Begin"
      aamh:
        spine1:
          - "spine1-base"
          - "Spine-1-AAMH-Begin"
        spine2:
          - "spine2-base"
          - "Spine-2-AAMH-Begin"
        spine3:
          - "spine3-base"
          - "Spine-3-AAMH-Begin"
        leaf1:
          - "leaf1-base"
          - "Leaf-1-AAMH-Begin"
        leaf2:
          - "leaf2-base"
          - "Leaf-2-AAMH-Begin"
        leaf3:
          - "leaf3-base"
          - "Leaf-3-AAMH-Begin"
        leaf4:
          - "leaf4-base"
          - "Leaf-4-AAMH-Begin"
        host1:
          - "host1-base"
          - "Host-1-AAMH-Begin"
        host2:
          - "host2-base"
          - "Host-2-AAMH-Begin"
        borderleaf1:
          - "borderleaf1-base"
          - "Borderleaf-1-AAMH-Begin"
        borderleaf2:
          - "borderleaf2-base"
          - "Borderleaf-2-AAMH-Begin"
      pim:
        spine1:
          - "spine1-base"
          - "Spine-1-PIM-Begin"
        spine2:
          - "spine2-base"
          - "Spine-2-PIM-Begin"
        spine3:
          - "spine3-base"
          - "Spine-3-PIM-Begin"
        leaf1:
          - "leaf1-base"
          - "Leaf-1-PIM-Begin"
        leaf2:
          - "leaf2-base"
          - "Leaf-2-PIM-Begin"
        leaf3:
          - "leaf3-base"
          - "Leaf-3-PIM-Begin"
        leaf4:
          - "leaf4-base"
          - "Leaf-4-PIM-Begin"
        host1:
          - "host1-base"
          - "Host-1-PIM-Begin"
        host2:
          - "host2-base"
          - "Host-2-PIM-Begin"
        borderleaf1:
          - "borderleaf1-base"
          - "Borderleaf-1-PIM-Begin"
        borderleaf2:
          - "borderleaf2-base"
          - "Borderleaf-2-PIM-Begin"