"""
Unit tests for bridge name generation and parsing consistency.

Tests cover:
- Bridge name generation for all device types
- Consistency with captureservice parsing
- OVS 15-character limit compliance
- Device name abbreviation conventions
- VeloCloud port naming

These tests ensure that bridge names generated by nodebuilder can be
correctly parsed back to device/port names by captureservice for the
capture panel and link impairments feature.
"""

import pytest
from interface_manager import parse_device_name, generate_bridge_name


class TestParseDeviceName:
    """Test device name parsing for bridge name generation."""

    def test_spine_parsing(self):
        """Test spine device name parsing."""
        result = parse_device_name('spine1')
        assert result['code'] == 'sp1'
        assert result['name'] == 'spine1'

    def test_leaf_parsing(self):
        """Test leaf device name parsing."""
        result = parse_device_name('leaf1')
        assert result['code'] == 'le1'

    def test_borderleaf_parsing(self):
        """Test borderleaf device name parsing."""
        result = parse_device_name('borderleaf1')
        assert result['code'] == 'bo1'  # First 2 letters, not 'bl'

    def test_firewall_parsing(self):
        """Test firewall device name parsing."""
        result = parse_device_name('firewall1')
        assert result['code'] == 'fi1'  # First 2 letters, not 'fw'

    def test_gateway_parsing(self):
        """Test gateway device name parsing."""
        result = parse_device_name('gateway1')
        assert result['code'] == 'ga1'  # First 2 letters, not 'gw'

    def test_host_parsing(self):
        """Test host device name parsing."""
        result = parse_device_name('host1')
        assert result['code'] == 'ho1'

    def test_velocloud_edge_parsing(self):
        """Test VeloCloud Edge device name parsing."""
        result = parse_device_name('vce1')
        assert result['code'] == 'vc1'

    def test_velocloud_gateway_parsing(self):
        """Test VeloCloud Gateway device name parsing."""
        result = parse_device_name('vcg1')
        assert result['code'] == 'vc1'

    def test_velocloud_orchestrator_parsing(self):
        """Test VeloCloud Orchestrator device name parsing."""
        result = parse_device_name('vco1')
        assert result['code'] == 'vc1'

    def test_ethernet_port_parsing(self):
        """Test Ethernet port name parsing."""
        result = parse_device_name('Ethernet1')
        assert result['code'] == '1'  # Just the number for Ethernet

        result = parse_device_name('Ethernet12')
        assert result['code'] == '12'

    def test_case_insensitive(self):
        """Test that parsing is case-insensitive."""
        result1 = parse_device_name('Spine1')
        result2 = parse_device_name('SPINE1')
        result3 = parse_device_name('spine1')

        assert result1['code'] == result2['code'] == result3['code']

    def test_dc_suffix(self):
        """Test parsing device names with -dc suffix."""
        result = parse_device_name('spine1-dc1')
        # Should include DC suffix in code
        assert 'sp1' in result['code'] or 'd1' in result['code']

    def test_high_device_numbers(self):
        """Test parsing devices with high numbers."""
        result = parse_device_name('leaf15')
        assert result['code'] == 'le15'

        result = parse_device_name('spine24')
        assert result['code'] == 'sp24'


class TestGenerateBridgeName:
    """Test OVS bridge name generation."""

    def test_basic_bridge_name(self):
        """Test basic bridge name generation."""
        name = generate_bridge_name('leaf1', 'Ethernet1', 'spine1', 'Ethernet2')
        assert '-' in name  # Should have separator
        assert len(name) <= 15  # OVS limit

    def test_uses_x_separator(self):
        """Test that nodebuilder format uses 'x' separator."""
        name = generate_bridge_name('leaf1', 'Ethernet1', 'spine1', 'Ethernet2')
        # Format: {dev1_code}x{port1}-{dev2_code}x{port2}
        assert 'x' in name

    def test_bridge_name_consistency(self):
        """Test that same inputs produce same output."""
        name1 = generate_bridge_name('leaf1', 'Ethernet1', 'spine1', 'Ethernet2')
        name2 = generate_bridge_name('leaf1', 'Ethernet1', 'spine1', 'Ethernet2')
        assert name1 == name2

    def test_case_normalized(self):
        """Test that bridge names are normalized to lowercase."""
        name1 = generate_bridge_name('Leaf1', 'Ethernet1', 'Spine1', 'Ethernet2')
        name2 = generate_bridge_name('leaf1', 'Ethernet1', 'spine1', 'Ethernet2')
        assert name1 == name2

    def test_different_ports_different_bridges(self):
        """Test that different ports produce different bridge names."""
        name1 = generate_bridge_name('leaf1', 'Ethernet1', 'spine1', 'Ethernet2')
        name2 = generate_bridge_name('leaf1', 'Ethernet2', 'spine1', 'Ethernet2')
        assert name1 != name2

    def test_ovs_length_limit(self):
        """Test that bridge names respect OVS 15-character limit."""
        # Even with long device names, should be <= 15 chars
        name = generate_bridge_name('borderleaf1', 'Ethernet12', 'spine24', 'Ethernet15')
        assert len(name) <= 15

    def test_firewall_bridge_name(self):
        """Test bridge name for firewall connections."""
        name = generate_bridge_name('firewall1', 'Ethernet1', 'borderleaf1', 'Ethernet5')
        # Should use 'fi' for firewall, not 'fw'
        assert 'fi1' in name
        assert 'bo1' in name

    def test_host_bridge_name(self):
        """Test bridge name for Linux host connections."""
        name = generate_bridge_name('host1', 'eth0', 'leaf1', 'Ethernet10')
        assert 'ho1' in name

    def test_velocloud_bridge_name(self):
        """Test bridge name for VeloCloud connections."""
        name = generate_bridge_name('vce1', 'wan1', 'router1', 'Ethernet1')
        assert 'vc1' in name or 've1' in name


class TestBridgeNameRoundTrip:
    """
    Test that bridge names can be parsed back to original device/port names.

    This simulates the integration between nodebuilder and captureservice:
    - nodebuilder generates bridge name
    - captureservice parses it back
    - The original device/port names should be recoverable

    Note: These tests use a simplified parser that mirrors captureservice logic.
    """

    # Device abbreviations from captureservice
    DEVICE_ABBREVIATIONS = {
        'sp': 'spine',
        'le': 'leaf',
        'bo': 'borderleaf',
        'ho': 'host',
        'fi': 'firewall',
        've': 'vce',
        'vc': 'vcg',
        'vo': 'vco',
        'cl': 'client',
        'co': 'core',
        'pe': 'pe',
        'ce': 'ce',
        'dc': 'dci',
        'rr': 'rr',
        'ga': 'gateway',
        'ro': 'router',
        'is': 'isp',
        'in': 'internet',
        'me': 'memleaf',
        'cu': 'customer',
        'oo': 'oob',
    }

    def _parse_bridge_name(self, bridge_name: str) -> dict:
        """Parse bridge name using captureservice logic."""
        import re

        result = {
            "source_device_name": "",
            "source_port_name": "",
            "target_device_name": "",
            "target_port_name": ""
        }

        if '-' not in bridge_name:
            return result

        parts = bridge_name.split('-')
        if len(parts) >= 2:
            src = parts[0]
            tgt = parts[1]

            src_device, src_port = self._split_device_port(src)
            tgt_device, tgt_port = self._split_device_port(tgt)

            result["source_device_name"] = self._expand_device_code(src_device)
            result["source_port_name"] = self._expand_port_code(src_port)
            result["target_device_name"] = self._expand_device_code(tgt_device)
            result["target_port_name"] = self._expand_port_code(tgt_port)

        return result

    def _split_device_port(self, part: str) -> tuple:
        """Split device+port string."""
        import re
        lower = part.lower()

        # Check for 'x' separator
        for i, c in enumerate(lower):
            if c == 'x' and i > 0 and i < len(part) - 1:
                prev_char = lower[i - 1]
                next_char = lower[i + 1]
                if prev_char.isdigit() and (next_char.isdigit() or next_char == 'e'):
                    return part[:i], part[i + 1:]

        # Look for 'eth'
        eth_idx = lower.find('eth')
        if eth_idx > 0:
            return part[:eth_idx], part[eth_idx:]

        # Look for 'et'
        et_idx = lower.find('et')
        if et_idx > 0:
            return part[:et_idx], part[et_idx:]

        # Legacy format
        match = re.match(r'^([a-zA-Z]{2})(\d)(\d+)$', part)
        if match:
            prefix = match.group(1)
            device_num = match.group(2)
            port_num = match.group(3).lstrip('0') or '0'
            return f"{prefix}{device_num}", port_num

        return part, ""

    def _expand_device_code(self, code: str) -> str:
        """Expand device code to full name."""
        if not code:
            return code

        prefix = ''
        number = ''
        for char in code:
            if char.isalpha():
                prefix += char
            elif char.isdigit():
                number += char

        prefix_lower = prefix.lower()
        if prefix_lower in self.DEVICE_ABBREVIATIONS:
            return f"{self.DEVICE_ABBREVIATIONS[prefix_lower]}{number}"

        return code

    def _expand_port_code(self, code: str) -> str:
        """Expand port code to full name."""
        if not code:
            return code

        code_lower = code.lower()

        if code_lower.startswith('eth'):
            return code

        if code_lower.startswith('wan') or code_lower.startswith('lan'):
            return code

        if code_lower.startswith('wa') and len(code) >= 3:
            number = ''.join(c for c in code if c.isdigit())
            if number:
                return f"wan{number}"

        if code_lower.startswith('la') and len(code) >= 3:
            number = ''.join(c for c in code if c.isdigit())
            if number:
                return f"lan{number}"

        if code_lower.startswith('et'):
            number = ''.join(c for c in code if c.isdigit())
            if number:
                return f"Ethernet{number}"

        if code.isdigit():
            return f"Ethernet{code}"

        return code

    def test_leaf_spine_roundtrip(self):
        """Test leaf to spine connection roundtrip."""
        bridge = generate_bridge_name('leaf1', 'Ethernet1', 'spine1', 'Ethernet2')
        result = self._parse_bridge_name(bridge)

        assert result['source_device_name'] == 'leaf1'
        assert result['source_port_name'] == 'Ethernet1'
        assert result['target_device_name'] == 'spine1'
        assert result['target_port_name'] == 'Ethernet2'

    def test_firewall_roundtrip(self):
        """Test firewall connection roundtrip (fi prefix)."""
        bridge = generate_bridge_name('firewall1', 'Ethernet1', 'borderleaf1', 'Ethernet5')
        result = self._parse_bridge_name(bridge)

        assert result['source_device_name'] == 'firewall1'
        assert result['source_port_name'] == 'Ethernet1'
        assert result['target_device_name'] == 'borderleaf1'
        assert result['target_port_name'] == 'Ethernet5'

    def test_gateway_roundtrip(self):
        """Test gateway connection roundtrip (ga prefix)."""
        bridge = generate_bridge_name('gateway1', 'Ethernet1', 'core1', 'Ethernet3')
        result = self._parse_bridge_name(bridge)

        assert result['source_device_name'] == 'gateway1'
        assert result['source_port_name'] == 'Ethernet1'
        assert result['target_device_name'] == 'core1'
        assert result['target_port_name'] == 'Ethernet3'

    def test_host_roundtrip(self):
        """Test Linux host connection roundtrip.

        Note: eth prefix is now preserved through the roundtrip to distinguish
        Linux host interfaces (eth0, eth1) from Ethernet ports (Ethernet1, et1).
        """
        bridge = generate_bridge_name('host1', 'eth0', 'leaf1', 'Ethernet10')
        result = self._parse_bridge_name(bridge)

        assert result['source_device_name'] == 'host1'
        # eth0 is preserved through roundtrip
        assert result['source_port_name'] == 'eth0'
        assert result['target_device_name'] == 'leaf1'
        assert result['target_port_name'] == 'Ethernet10'

    def test_high_port_numbers(self):
        """Test high port number connections."""
        bridge = generate_bridge_name('leaf1', 'Ethernet12', 'spine1', 'Ethernet24')
        result = self._parse_bridge_name(bridge)

        assert result['source_port_name'] == 'Ethernet12'
        assert result['target_port_name'] == 'Ethernet24'

    def test_high_device_numbers(self):
        """Test high device number connections."""
        bridge = generate_bridge_name('leaf15', 'Ethernet1', 'spine8', 'Ethernet1')
        result = self._parse_bridge_name(bridge)

        assert result['source_device_name'] == 'leaf15'
        assert result['target_device_name'] == 'spine8'

    def test_all_device_types(self):
        """Test roundtrip for all supported device types."""
        device_types = [
            ('spine1', 'spine1'),
            ('leaf1', 'leaf1'),
            ('borderleaf1', 'borderleaf1'),
            ('host1', 'host1'),
            ('firewall1', 'firewall1'),
            ('gateway1', 'gateway1'),
            ('router1', 'router1'),
            ('core1', 'core1'),
            ('customer1', 'customer1'),
            ('isp1', 'isp1'),
        ]

        for device_name, expected_name in device_types:
            bridge = generate_bridge_name(device_name, 'Ethernet1', 'leaf1', 'Ethernet2')
            result = self._parse_bridge_name(bridge)

            assert result['source_device_name'] == expected_name, f"Failed for {device_name}"


class TestDeviceAbbreviationConsistency:
    """
    Test that device abbreviations in nodebuilder match captureservice.

    This ensures that bridge names generated by nodebuilder can be
    correctly parsed by captureservice.
    """

    # Expected abbreviations: first 2 letters of device type
    EXPECTED_ABBREVIATIONS = {
        'spine': 'sp',
        'leaf': 'le',
        'borderleaf': 'bo',  # NOT 'bl'
        'host': 'ho',
        'firewall': 'fi',    # NOT 'fw'
        'gateway': 'ga',     # NOT 'gw'
        'router': 'ro',
        'core': 'co',
        'customer': 'cu',
        'isp': 'is',
        'internet': 'in',
        'memleaf': 'me',
        'oob': 'oo',
    }

    def test_abbreviation_pattern(self):
        """Test that parse_device_name uses first 2 letters."""
        for device_type, expected_abbrev in self.EXPECTED_ABBREVIATIONS.items():
            device_name = f"{device_type}1"
            result = parse_device_name(device_name)
            actual_abbrev = result['code'][:2]  # First 2 chars of code

            assert actual_abbrev == expected_abbrev, \
                f"{device_type}1 should abbreviate to {expected_abbrev}1, got {result['code']}"

    def test_no_legacy_abbreviations_in_generation(self):
        """Test that nodebuilder doesn't generate legacy abbreviations."""
        # These should NOT be generated by nodebuilder
        legacy_patterns = ['bl1', 'fw1', 'gw1']

        test_cases = [
            ('borderleaf1', 'Ethernet1', 'leaf1', 'Ethernet1'),
            ('firewall1', 'Ethernet1', 'leaf1', 'Ethernet1'),
            ('gateway1', 'Ethernet1', 'leaf1', 'Ethernet1'),
        ]

        for dev1, port1, dev2, port2 in test_cases:
            bridge = generate_bridge_name(dev1, port1, dev2, port2)

            for legacy in legacy_patterns:
                assert legacy not in bridge, \
                    f"Bridge {bridge} contains legacy pattern {legacy}"
