    lab_list:
      reset:
        description: "Reset All Devices to Base Lab (reset)"
      Start-of-Exam:
        description: "Reset All Device to the Start of Level 7 Part 2 Exam"
    labconfiglets:
      reset:
        A1:
          - a1-BASE
        B1:
          - b1-BASE
        C1:
          - c1-BASE
        A2:
          - a2-BASE
        B2:
          - b2-BASE
        C2:
          - c2-BASE
        PE1:
          - pe1-BASE
        PE2:
          - pe2-BASE
        P3:
          - p3-BASE
        P4:
          - p4-BASE
        P5:
          - p5-BASE
        P6:
          - p6-BASE
      CPNR:
        A1:
          - a1-BASE
          - A1-IP
        B1:
          - b1-BASE
          - B1-IP
        C1:
          - c1-BASE
          - C1-IP
        A2:
          - a2-BASE
          - A2-IP
        B2:
          - b2-BASE
          - B2-IP
        C2:
          - c2-BASE
          - C2-IP
        PE1:
          - pe1-BASE
          - PE1-IP
        PE2:
          - pe2-BASE
          - PE2-IP
        P3:
          - p3-BASE
          - P3-IP
        P4:
          - p4-BASE
          - P4-IP
        P5:
          - p5-BASE
          - P5-IP
        P6:
          - p6-BASE
          - P6-IP
      MPLS-LDP:
        A1:
          - a1-BASE
          - A1-ISIS
        B1:
          - b1-BASE
          - B1-ISIS
        C1:
          - c1-BASE
          - C1-ISIS
        A2:
          - a2-BASE
          - A2-ISIS
        B2:
          - b2-BASE
          - B2-ISIS
        C2:
          - c2-BASE
          - C2-ISIS
        PE1:
          - pe1-BASE
          - PE1-ISIS
        PE2:
          - pe2-BASE
          - PE2-ISIS
        P3:
          - p3-BASE
          - P3-ISIS
        P4:
          - p4-BASE
          - P4-ISIS
        P5:
          - p5-BASE
          - P5-ISIS
        P6:
          - p6-BASE
          - P6-ISIS
      ISIS-SR:
        A1:
          - a1-BASE
          - A1-LDP
        B1:
          - b1-BASE
          - B1-LDP
        C1:
          - c1-BASE
          - C1-LDP
        A2:
          - a2-BASE
          - A2-LDP
        B2:
          - b2-BASE
          - B2-LDP
        C2:
          - c2-BASE
          - C2-LDP
        PE1:
          - pe1-BASE
          - PE1-LDP
        PE2:
          - pe2-BASE
          - PE2-LDP
        P3:
          - p3-BASE
          - P3-LDP
        P4:
          - p4-BASE
          - P4-LDP
        P5:
          - p5-BASE
          - P5-LDP
        P6:
          - p6-BASE
          - P6-LDP
      SR-TE:
        A1:
          - a1-BASE
          - A1-ISIS-SR
        B1:
          - b1-BASE
          - B1-ISIS-SR
        C1:
          - c1-BASE
          - C1-ISIS-SR
        A2:
          - a2-BASE
          - A2-ISIS-SR
        B2:
          - b2-BASE
          - B2-ISIS-SR
        C2:
          - c2-BASE
          - C2-ISIS-SR
        PE1:
          - pe1-BASE
          - PE1-ISIS-SR
        PE2:
          - pe2-BASE
          - PE2-ISIS-SR
        P3:
          - p3-BASE
          - P3-ISIS-SR
        P4:
          - p4-BASE
          - P4-ISIS-SR
        P5:
          - p5-BASE
          - P5-ISIS-SR
        P6:
          - p6-BASE
          - P6-ISIS-SR
      SR-TE-Policy:
        A1:
          - a1-BASE
          - A1-ROUTER-TE
        B1:
          - b1-BASE
          - B1-ROUTER-TE
        C1:
          - c1-BASE
          - C1-ROUTER-TE
        A2:
          - a2-BASE
          - A2-ROUTER-TE
        B2:
          - b2-BASE
          - B2-ROUTER-TE
        C2:
          - c2-BASE
          - C2-ROUTER-TE
        PE1:
          - pe1-BASE
          - PE1-ROUTER-TE
        PE2:
          - pe2-BASE
          - PE2-ROUTER-TE
        P3:
          - p3-BASE
          - P3-ROUTER-TE
        P4:
          - p4-BASE
          - P4-ROUTER-TE
        P5:
          - p5-BASE
          - P5-ROUTER-TE
        P6:
          - p6-BASE
          - P6-ROUTER-TE
      Steering-TE-Policy:
        A1:
          - a1-BASE
          - A1-SR-TE-POLICY
        B1:
          - b1-BASE
          - B1-SR-TE-POLICY
        C1:
          - c1-BASE
          - C1-SR-TE-POLICY
        A2:
          - a2-BASE
          - A2-SR-TE-POLICY
        B2:
          - b2-BASE
          - B2-SR-TE-POLICY
        C2:
          - c2-BASE
          - C2-SR-TE-POLICY
        PE1:
          - pe1-BASE
          - PE1-SR-TE-POLICY
        PE2:
          - pe2-BASE
          - PE2-SR-TE-POLICY
        P3:
          - p3-BASE
          - P3-SR-TE-POLICY
        P4:
          - p4-BASE
          - P4-SR-TE-POLICY
        P5:
          - p5-BASE
          - P5-SR-TE-POLICY
        P6:
          - p6-BASE
          - P6-SR-TE-POLICY
      MP-BGP-L3EVPN:
        A1:
          - a1-BASE
          - A1-TRAFFIC-STEERING
        B1:
          - b1-BASE
          - B1-TRAFFIC-STEERING
        C1:
          - c1-BASE
          - C1-TRAFFIC-STEERING
        A2:
          - a2-BASE
          - A2-TRAFFIC-STEERING
        B2:
          - b2-BASE
          - B2-TRAFFIC-STEERING
        C2:
          - c2-BASE
          - C2-TRAFFIC-STEERING
        PE1:
          - pe1-BASE
          - PE1-TRAFFIC-STEERING
        PE2:
          - pe2-BASE
          - PE2-TRAFFIC-STEERING
        P3:
          - p3-BASE
          - P3-TRAFFIC-STEERING
        P4:
          - p4-BASE
          - P4-TRAFFIC-STEERING
        P5:
          - p5-BASE
          - P5-TRAFFIC-STEERING
        P6:
          - p6-BASE
          - P6-TRAFFIC-STEERING
      Start-of-Exam:
        A1:
          - a1-BASE
          - A1-L3-VPN
        B1:
          - b1-BASE
          - B1-L3-VPN
        
