---
    lab_list:
      reset:
        additional_commands: 
          - "bash /home/arista/Broadcaster/pushHostDefaultConfig.sh"
        description: "Reset All Devices to Base Lab (reset)"
    labconfiglets:
      reset:
        spine1:
          - "spine1-base"
        spine2:
          - "spine2-base"
        spine3:
          - "spine3-base"
        spine4:
          - "spine4-base"
        leaf1:
          - "leaf1-base"
        leaf2:
          - "leaf2-base"
        leaf3:
          - "leaf3-base"
        leaf4:
          - "leaf4-base"
        host1:
          - "host1-base"
        host2:
          - "host2-base"
        borderleaf1:
          - "borderleaf1-base"
        borderleaf2:
          - "borderleaf2-base"
